import { Router } from 'express';
import { healthRouter } from '../modules/health/health.routes.js';
import { tenantsRouter } from '../modules/tenants/tenants.routes.js';
import { authRouter } from '../modules/auth/auth.routes.js';
import { rolesRouter } from '../modules/roles/roles.routes.js';
import { permissionsRouter } from '../modules/permissions/permissions.routes.js';
import { usersRouter } from '../modules/users/users.routes.js';
import { categoriesRouter } from '../modules/categories/categories.routes.js';
import { productsRouter } from '../modules/products/products.routes.js';
import { variantsRouter } from '../modules/variants/variants.routes.js';
import { attributesRouter } from '../modules/attributes/attributes.routes.js';
import { productImagesRouter } from '../modules/product-images/product-images.routes.js';
import { inventoryRouter } from '../modules/inventory/inventory.routes.js';
import { warehousesRouter } from '../modules/warehouses/warehouses.routes.js';

export const apiRouter = Router();
apiRouter.use('/health', healthRouter);
apiRouter.use('/tenants', tenantsRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/roles', rolesRouter);
apiRouter.use('/permissions', permissionsRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/categories', categoriesRouter);
apiRouter.use('/products', productsRouter);
apiRouter.use('/products/:productId/variants', variantsRouter);
apiRouter.use('/attributes', attributesRouter);
apiRouter.use('/warehouses', warehousesRouter);
apiRouter.use('/inventory', inventoryRouter);
apiRouter.use('/', productImagesRouter);