import { Router } from 'express';
import { healthRouter } from '../modules/health/health.routes.js';
import { tenantsRouter } from '../modules/tenants/tenants.routes.js';
import { authRouter } from '../modules/auth/auth.routes.js';
import { rolesRouter } from '../modules/roles/roles.routes.js';
import { permissionsRouter } from '../modules/permissions/permissions.routes.js';
import { usersRouter } from '../modules/users/users.routes.js';
import { categoriesRouter } from '../modules/categories/categories.routes.js';
import { productsRouter } from '../modules/products/products.routes.js';
import { variantsRouter } from '../modules/variants/variants.routes.js';
import { attributesRouter } from '../modules/attributes/attributes.routes.js';
import { productImagesRouter } from '../modules/product-images/product-images.routes.js';
import { inventoryRouter } from '../modules/inventory/inventory.routes.js';
import { warehousesRouter } from '../modules/warehouses/warehouses.routes.js';
import { ordersRouter } from '../modules/orders/orders.routes.js';
import { paymentsRouter } from '../modules/payments/payments.routes.js';
import { auditRouter, activityRouter } from '../modules/audit/audit.routes.js';
import { notificationsRouter, notificationPreferencesRouter } from '../modules/notifications/notifications.routes.js';
import { jobsRouter } from '../modules/jobs/jobs.routes.js';
import { dashboardRouter } from '../modules/dashboard/dashboard.routes.js';
import { analyticsRouter } from '../modules/analytics/analytics.routes.js';
import { storageRouter } from '../modules/storage/storage.routes.js';
import { platformRouter } from '../modules/platform/platform.routes.js';

export const apiRouter = Router();
apiRouter.use('/health', healthRouter);
apiRouter.use('/tenants', tenantsRouter);
apiRouter.use('/platform', platformRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/roles', rolesRouter);
apiRouter.use('/permissions', permissionsRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/categories', categoriesRouter);
apiRouter.use('/products', productsRouter);
apiRouter.use('/products/:productId/variants', variantsRouter);
apiRouter.use('/attributes', attributesRouter);
apiRouter.use('/warehouses', warehousesRouter);
apiRouter.use('/inventory', inventoryRouter);
apiRouter.use('/orders', ordersRouter);
apiRouter.use('/payments', paymentsRouter);
apiRouter.use('/audit-logs', auditRouter);
apiRouter.use('/activity-logs', activityRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/notification-preferences', notificationPreferencesRouter);
apiRouter.use('/jobs', jobsRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/storage', storageRouter);
apiRouter.use('/', productImagesRouter);